engine.name=client
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://db_client:5432/clientdb
db.user=postgres
db.password=postgres

group.id=client
external.id=001

registration.url=http://symmetricds_server:31415/sync/server
sync.url=http://symmetricds_client:31416/sync/client

# Enable schema sync
sync.table.structure=true
sync.triggers.ddl.sql=true
auto.config.database=true

http.port=31416
