engine.name=server
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://db_server:5432/serverdb
db.user=postgres
db.password=postgres

group.id=server
external.id=000

registration.url=http://symmetricds_server:31415/sync/server
sync.url=http://symmetricds_server:31415/sync/server


# Enable auto table sync
sync.table.structure=true
sync.triggers.ddl.sql=true
auto.config.database=true
auto.sync.triggers=true
auto.sync.triggers.mode=all

# Initial load behavior
initial.load.create.first=true
initial.load.delete.first=false
